version: '3.8'

services:
  web:
    image: ghcr.io/byamungu1/mycompeta-shop-web-version:latest
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-/api/}
        VITE_CART_STORAGE_KEY: ${VITE_CART_STORAGE_KEY:-user_shopping_cart}
        VITE_DIRECT_BUY_STORAGE_KEY: ${VITE_DIRECT_BUY_STORAGE_KEY:-directBuyProduct}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-}
        VITE_GOOGLE_REDIRECT_URL: ${VITE_GOOGLE_REDIRECT_URL:-}
    container_name: competa-shop-web
    ports:
      - "3000:10000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge